### ISSUE TITLE
Error: getaddrinfo ENOTFOUND [::1]

### ISSUE THREAD

**Issue by ghost** [BitDesert/nano-node-rpc#1]
When using any method:
`Error: getaddrinfo ENOTFOUND [::1]     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {   errno: -3008,   code: 'ENOTFOUND',   syscall: 'getaddrinfo',   hostname: '[::1]' }`

**Comment by BitDesert** [comment]
What's the node URL you specified?
